insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r464','Frys.com Open','San Martin, CA','2013-10-10','2013-10-13','Jimmy Walker');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r504','PGA Grand Slam of Golf','Southampton Parish, BER','2013-10-14','2013-10-16','Adam Scott');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r047','Shriners Hospitals for Children Open','Las Vegas, NV','2013-10-17','2013-10-20','Webb Simpson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r494','CIMB Classic','Kuala Lumpur, MAS','2013-10-24','2013-10-27','Nick Watney');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r489','World Golf Championships-HSBC Champions','Shanghai, CHN','2013-10-31','2013-11-03','Ian Poulter');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r493','The McGladrey Classic','Sea Island, GA','2013-11-07','2013-11-10','Tommy Gainey');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r324','Wendy`s 3-Tour Challenge','Henderson, NV','2013-11-11','2013-11-12','Jason Day');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r457','OHL Classic at Mayakoba','Riviera Maya, Mex','2013-11-14','2013-11-17','John Huh');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r169','ISPS HANDA World Cup of Golf','Melbourne, AUS','2013-11-21','2013-11-24','Matt Kuchar');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r478','Northwestern Mutual World Challenge','Thousand Oaks, CA','2013-12-05','2013-12-08','Graeme McDowell');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r058','Franklin Templeton Shootout','Naples, FL','2013-12-13','2013-12-15','Sean OHair');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r016','Hyundai Tournament of Champions','Kapalua, HI','2014-01-03','2014-01-06','Dustin Johnson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r006','Sony Open in Hawaii','Honolulu, HI','2014-01-09','2014-01-12','Russell Henley');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r002','Humana Challenge in partnership with the Clinton Foundation','La Quinta, CA','2014-01-16','2014-01-19','Brian Gay');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r004','Farmers Insurance Open','La Jolla, CA','2014-01-23','2014-01-26','Tiger Woods');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r003','Waste Management Phoenix Open','Scottsdale, AZ','2014-01-30','2014-02-02','Phil Mickelson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r005','ATT Pebble Beach National Pro-Am','Pebble Beach, CA','2014-02-06','2014-02-09','Brandt Snedeker');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r007','Northern Trust Open','Pacific Palisades, CA','2014-02-13','2014-02-16','John Merrick');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r470','World Golf Championships-Accenture Match Play Championship','Marana, AZ','2014-02-19','2014-02-23','Matt Kuchar');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r010','The Honda Classic','Palm Beach Gardens, FL','2014-02-27','2014-03-02','Michael Thompson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r483','Puerto Rico Open presented by seepuertorico.com','Rio Grande, PUR','2014-03-06','2014-03-09','Scott Brown');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r473','World Golf Championships-Cadillac Championship','Miami, FL','2014-03-06','2014-03-09','Tiger Woods');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r475','Valspar Championship','Palm Harbor, FL','2014-03-13','2014-03-16','Kevin Streelman');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r009','Arnold Palmer Invitational presented by MasterCard','Orlando, FL','2014-03-20','2014-03-23','Tiger Woods');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r041','Valero Texas Open','San Antonio, TX','2014-03-27','2014-03-30','Martin Laird');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r020','Shell Houston Open','Humble, TX','2014-04-03','2014-04-06','D.A. Points');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r014','Masters Tournament','Augusta, GA','2014-04-10','2014-04-13','Adam Scott');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r012','RBC Heritage','Hilton Head, SC','2014-04-17','2014-04-20','Graeme McDowell');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r018','Zurich Classic of New Orleans','Avondale, LA','2014-04-24','2014-04-27','Billy Horschel');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r480','Wells Fargo Championship','Charlotte, NC','2014-05-01','2014-05-04','Derek Ernst');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r011','THE PLAYERS Championship','Ponte Vedra Beach, FL','2014-05-08','2014-05-11','Tiger Woods');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r019','HP Byron Nelson Championship','Irving, TX','2014-05-15','2014-05-18','Sang-Moon Bae');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r021','Crowne Plaza Invitational at Colonial','Ft. Worth, TX','2014-05-22','2014-05-25','Boo Weekley');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r023','the Memorial Tournament presented by Nationwide Insurance','Dublin, OH','2014-05-29','2014-06-01','Matt Kuchar');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r025','FedEx St. Jude Classic','Memphis, TN','2014-06-05','2014-06-08','Harris English');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r026','U.S. Open','Pinehurst, NC','2014-06-12','2014-06-15','Justin Rose');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r034','Travelers Championship','Cromwell, CT','2014-06-19','2014-06-22','Ken Duke');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r486','CVS Caremark Charity Classic','Barrington, RI','2014-06-23','2014-06-24','Steve Stricker');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r471','ATT National','Bethesda, MD','2014-06-26','2014-06-29','Bill Haas');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r490','The Greenbrier Classic','White Sulphur Springs, WV','2014-07-03','2014-07-06','Jonas Blixt');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r030','John Deere Classic','Silvis, IL','2014-07-10','2014-07-13','Jordan Spieth');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r100','The Open Championship','Hoylake, Eng','2014-07-17','2014-07-20','Phil Mickelson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r032','RBC Canadian Open','Ile Bizard, CAN','2014-07-24','2014-07-27','Brandt Snedeker');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r472','Reno-Tahoe Open','Reno, NV','2014-07-31','2014-08-03','Gary Woodland');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r476','World Golf Championships-Bridgestone Invitational','Akron, OH','2014-07-31','2014-08-03','Tiger Woods');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r033','PGA Championship','Louisville, KY','2014-08-07','2014-08-10','Jason Dufner');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r013','Wyndham Championship','Greensboro, NC','2014-08-14','2014-08-17','Patrick Reed');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r027','The Barclays','Paramus, NJ','2014-08-21','2014-08-24','Adam Scott');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r505','Deutsche Bank Championship','Norton, MA','2014-08-29','2014-09-01','Henrik Stenson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r028','BMW Championship','Englewood, CO','2014-09-04','2014-09-07','Zach Johnson');
insert into tournament (tournament_id, name, location, start_date, end_date, prev_winner) values('r060','TOUR Championship by Coca-Cola','Atlanta, GA','2014-09-11','2014-09-14','Henrik Stenson');
